#Config Version 1 by Yukun
Options:
  ###################
  # General Options #
  ###################
  #Whether to strip the item from the player's off hand too. Only works for 1.9 and above.
  StripOffHand: 'false'
  
  ###################
  # Message Options #
  ###################
  #Whether to send Stripped message
  StrippedMessage: 'true'